apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: corn-field-k8s
  namespace: argo
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  sourceRepos:
  - '*'