apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  annotations:
    app-repo-url: https://github.com/TerryYin1777/corn-field-k8s.git
  namespace: argo
spec:
  project: corn-field-k8s
  source:
    repoURL: https://github.com/TerryYin1777/corn-field-k8s.git
    targetRevision: HEAD
    path: applications
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo